'use strict';
window.WG_Community=(function(){
  var $=function(id){return document.getElementById(id);},epoch=0,home=null,tabName='friends',scope=null,reply=null,challenge=null,socket=null,countdown=null,libraries=null,profileDirty=false,loadSerial=0;
  var api=function(method,path,body){return WG_API.req(method,'/api/community/'+path,body);};
  function el(parent,tag,value,cls){var n=document.createElement(tag);if(value!==undefined)n.textContent=value;if(cls)n.className=cls;parent.appendChild(n);return n;}
  function button(parent,value,fn,primary){var b=el(parent,'button',value,'btn '+(primary?'primary':'ghost'));b.type='button';b.onclick=function(){run(b,fn);};return b;}
  function message(value){$('communityMessage').textContent=value;}
  function date(value){return new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});}
  async function run(b,fn){if(b.disabled)return;var s=epoch;b.disabled=true;b.setAttribute('aria-busy','true');try{await fn(s);}catch(e){if(s===epoch)message(e.message||'操作失败，请重试');}finally{b.disabled=false;b.removeAttribute('aria-busy');}}
  function cloud(){if(WG_API.isCloudSession())return true;message('请先登录云端账号，才能添加学习搭子、留言或挑战。');return false;}
  function math(node){if(window.renderMathInElement)renderMathInElement(node,{delimiters:[{left:'\\(',right:'\\)',display:false},{left:'\\[',right:'\\]',display:true},{left:'$$',right:'$$',display:true}],throwOnError:false,trust:false});}
  function markdown(body,source,parser){
    var saved=[],prefix='XWYMATH'+crypto.randomUUID().replace(/-/g,'')+'TOKEN';
    var safe=source.replace(/\\\([\s\S]*?\\\)|\\\[[\s\S]*?\\\]|\$\$[\s\S]*?\$\$/g,function(value){var index=saved.push(value)-1;return prefix+index+'END';});
    body.innerHTML=parser.render(safe);
    // Restore formula delimiters as text nodes, never as raw HTML or attributes.
    var walk=document.createTreeWalker(body,NodeFilter.SHOW_TEXT),nodes=[],node;
    while((node=walk.nextNode()))nodes.push(node);
    var pattern=new RegExp(prefix+'(\\d+)END','g');
    nodes.forEach(function(n){n.nodeValue=n.nodeValue.replace(pattern,function(_,index){return saved[Number(index)];});});
    body.querySelectorAll('a').forEach(function(a){a.rel='nofollow noreferrer';});math(body);
  }
  function library(){if(libraries)return libraries;libraries=Promise.all([['/vendor/socketio/socket.io.min.js','io'],['/vendor/markdown-it/markdown-it.min.js','markdownit']].map(function(item){if(window[item[1]])return Promise.resolve();return new Promise(function(resolve,reject){var s=document.createElement('script');s.src=WG_Runtime.asset(item[0]);s.onload=resolve;s.onerror=function(){reject(new Error('校园互动资源加载失败，请重新启动网站后刷新'));};document.head.appendChild(s);});})).catch(function(e){libraries=null;throw e;});return libraries;}
  async function connect(){var session=epoch;if(!cloud())return;await library();if(session!==epoch||socket)return;
    socket=io((WG_API.getBase()||location.origin)+'/community',{auth:function(cb){cb({token:WG_API.getToken()});}});
    socket.on('connect',function(){$('communityConnection').textContent='实时通知已连接';});socket.on('disconnect',function(){$('communityConnection').textContent='连接中断，可手动刷新';});socket.on('connect_error',function(){$('communityConnection').textContent='通知暂不可用，可手动刷新';});
    socket.on('community:changed',function(event){if(session!==epoch)return;$('communityNotice').hidden=false;$('communityNotice').firstElementChild.textContent=event.kind==='posts'?'有新的留言或回复，刷新后查看。':'搭子或挑战状态已更新，刷新后查看。';window.dispatchEvent(new CustomEvent('xwy:community-changed',{detail:event}));});
  }
  function tab(name){tabName=name;document.querySelectorAll('[data-community-tab]').forEach(function(b){var on=b.dataset.communityTab===name;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;$('community-'+b.dataset.communityTab).hidden=!on;});}
  function fillSelect(node,items,first){var old=node.value;node.replaceChildren();if(first){var o=el(node,'option',first);o.value='';}items.forEach(function(item){var o=el(node,'option',item.label);o.value=item.value;});if(items.some(function(i){return i.value===old;}))node.value=old;}
  function renderHome(){if(!home)return;
    if(!profileDirty){$('buddyNick').value=home.profile.nick;$('buddyGoal').value=home.profile.goal;$('buddyAvailability').value=home.profile.availability;$('buddyVisible').checked=home.profile.visible;$('buddySubjects').replaceChildren();home.subjects.forEach(function(s){var label=el($('buddySubjects'),'label',undefined,'community-check'),input=el(label,'input');input.type='checkbox';input.value=s;input.name='buddySubject';input.checked=home.profile.subjects.includes(s);el(label,'span',s);});}
    if($('buddyFilter').options.length<2)fillSelect($('buddyFilter'),home.subjects.map(function(s){return{label:s,value:s};}),'全部课程');
    fillSelect($('challengeFriend'),home.friends.map(function(p){return{label:p.nick,value:p.id};}),home.friends.length?'选择学习搭子':'先添加学习搭子');
    fillSelect($('challengeTopic'),home.topics.map(function(t){return{label:t.topic+' · '+t.count+' 道客观题',value:t.topic};}));
    $('buddyDirectory').replaceChildren();if(!home.directory.length)el($('buddyDirectory'),'p','暂时没有符合条件的公开名片。你可以公开自己的名片，邀请同学注册后一起学习。','community-empty');
    home.directory.forEach(function(p){var item=personCard($('buddyDirectory'),p),pending=home.requests.find(function(r){return r.person.id===p.id;}),actions=el(item,'div',undefined,'community-actions');
      if(p.isFriend)el(actions,'span','已是学习搭子','community-muted');else if(pending)el(actions,'span',pending.from===home.uid?'邀请待确认':'对方已邀请你','community-muted');else button(actions,'邀请成为搭子',async function(s){await api('POST','request',{to:p.id,message:'一起学习 '+p.subjects.join('、')});if(s===epoch){message('邀请已发送，等待对方确认。');await loadHome(s);}});
    });
    $('buddyRequests').replaceChildren();home.requests.forEach(function(r){var item=el($('buddyRequests'),'article',undefined,'buddy-request');el(item,'strong',r.person.nick+(r.to===home.uid?' 邀请你成为搭子':' · 等待确认'));el(item,'p',r.message||'一起学习');var actions=el(item,'div',undefined,'community-actions');(r.to===home.uid?[['接受','accept'],['婉拒','reject']]:[['取消邀请','cancel']]).forEach(function(a){button(actions,a[0],async function(s){await api('PUT','request',{id:r.id,action:a[1]});if(s===epoch){message(a[0]+'成功。');await loadHome(s);}});});});
    $('buddyFriends').replaceChildren();el($('buddyFriends'),'h3','我的学习搭子 · '+home.friends.length);if(!home.friends.length)el($('buddyFriends'),'p','还没有学习搭子，先在广场发出邀请。','community-empty');home.friends.forEach(function(p){var item=personCard($('buddyFriends'),p),actions=el(item,'div',undefined,'community-actions');button(actions,'发起挑战',function(){tab('arena');$('challengeFriend').value=p.id;return loadChallenges(epoch);},true);button(actions,'解除搭子',async function(s){if(!confirm('解除与 '+p.nick+' 的搭子关系？'))return;await api('DELETE','friend',{id:p.id});if(s===epoch)await loadHome(s);});});
  }
  function personCard(parent,p){var item=el(parent,'article',undefined,'buddy-person');item.dataset.person=p.id;var head=el(item,'div',undefined,'buddy-person-head');el(head,'span',p.nick.slice(0,1),'buddy-avatar');var info=el(head,'div');el(info,'strong',p.nick);el(info,'p',p.online?'当前在线':'当前离线');var tags=el(item,'div',undefined,'buddy-tags');p.subjects.forEach(function(s){el(tags,'span',s);});if(p.goal)el(item,'p',p.goal);if(p.availability)el(item,'p','学习时间：'+p.availability);return item;}
  async function loadHome(s){var serial=++loadSerial,r=await api('GET','home?subject='+encodeURIComponent($('buddyFilter').value)+'&search='+encodeURIComponent($('buddySearchText').value));if(s!==epoch||serial!==loadSerial)return;home=r;renderHome();}
  async function load(){if(!cloud())return;var s=epoch;try{await connect();await loadHome(s);if(s!==epoch)return;if(tabName==='posts')await loadPosts(s);if(tabName==='arena')await loadChallenges(s);$('communityNotice').hidden=true;}catch(e){if(s===epoch)message(e.message);}}
  async function loadPosts(s){var requested=scope,r=await api('GET','posts'+(requested?'?qid='+encodeURIComponent(requested):''));if(s!==epoch||scope!==requested)return;var list=$('postList');list.replaceChildren();$('postScopeTitle').textContent=r.question?'题目讨论 · '+r.question.topic:'校园留言亭';$('postQuestion').replaceChildren();if(r.question)math(el($('postQuestion'),'p','题号 '+r.question.id+'：'+r.question.question));
    if(!r.posts.length)el(list,'p','还没有留言，分享你的想法，或写下第一份解题思路。','community-empty');
    var parser=markdownit({html:false,breaks:true,linkify:false});parser.disable('image');
    r.posts.forEach(function(p){var item=el(list,'article',undefined,'community-post'+(p.parent?' reply':''));item.dataset.post=p.id;var header=el(item,'div',undefined,'community-post-header');el(header,'strong',p.author.nick);var time=el(header,'time',date(p.createdAt));time.dateTime=new Date(p.createdAt).toISOString();if(p.parent){var original=r.posts.find(function(x){return x.id===p.parent;});el(item,'p','回复 '+(original?original.author.nick:'此前的留言'),'community-muted');}
      var body=el(item,'div',undefined,'community-markdown');if(p.deleted)body.textContent='这条留言已由作者删除。';else markdown(body,p.text,parser);
      if(!p.deleted){var actions=el(item,'div',undefined,'community-actions');button(actions,'回复',function(){reply=p.id;$('postReplyContext').textContent='正在回复 '+p.author.nick;$('postCancelReply').hidden=false;$('postText').focus();});if(p.canDelete)button(actions,'删除',async function(session){if(!confirm('删除这条留言？'))return;await api('DELETE','posts',{id:p.id});if(session===epoch){await loadPosts(session);message('留言已删除。');}});}
    });
  }
  function clearReply(){reply=null;$('postReplyContext').textContent='';$('postCancelReply').hidden=true;}
  var labels={active:'进行中',completed:'已完成',cancelled:'已取消',expired:'已过期'};
  async function loadChallenges(s){var r=await api('GET','challenges');if(s!==epoch)return;var list=$('challengeList');list.replaceChildren();if(!r.challenges.length)el(list,'p','还没有挑战。邀请搭子完成同一组题，再一起讨论。','community-empty');r.challenges.forEach(function(c){var item=el(list,'article',undefined,'challenge-item');item.dataset.challenge=c.id;item.dataset.status=c.status;el(item,'strong',c.topic+' · '+c.peer.nick);el(item,'p',labels[c.status]+' · '+date(c.createdAt));el(item,'p',(c.mine.finishedAt?'你已交卷':'你尚未交卷')+' · '+(c.opponent.submitted?'搭子已交卷':'搭子尚未交卷'));button(item,c.status==='completed'?'查看复盘':'查看挑战',function(session){return openChallenge(c.id,session);});});}
  async function openChallenge(id,s){var r=await api('GET','challenge?id='+encodeURIComponent(id));if(s!==epoch)return;challenge=r.challenge;renderChallenge();}
  function renderChallenge(){clearInterval(countdown);var root=$('challengeDetail');root.replaceChildren();if(!challenge)return;var c=challenge;el(root,'h2',c.topic+' · 与 '+c.peer.nick+' 的挑战');el(root,'p',labels[c.status]+' · 五题 · 每人限时 15 分钟','community-muted');
    if(c.status==='completed'){el(root,'p',c.winner===home.uid?'你赢得了这次挑战':c.winner?'这次搭子领先，一起看看解题过程':'本次平局','challenge-score');el(root,'p','你答对 '+c.mine.score+'/5 · 用时 '+seconds(c.mine.elapsedMs)+'；搭子答对 '+c.opponent.score+'/5 · 用时 '+seconds(c.opponent.elapsedMs));c.review.forEach(function(q,i){var item=el(root,'article',undefined,'challenge-review');el(item,'strong',String(i+1)+' · '+(q.correct?'答对':'待巩固'));math(el(item,'p',q.question,'community-question'));el(item,'p','你的答案：'+(q.yours||'未答')+' · 标准答案：'+q.answer);var detail=el(item,'details',undefined,'challenge-analysis');el(detail,'summary','展开解题解析');math(el(detail,'div',q.analysis,'community-question'));var actions=el(item,'div',undefined,'community-actions');button(actions,'讨论这道题',function(){openQuestion(q.qid);});button(actions,'打开题目白板',function(){WG_Learning.openBoard({qid:q.qid,question:q.question,topic:q.topic});});});return;}
    if(c.status!=='active'){el(root,'p','这场挑战已结束，可重新发起挑战。','community-empty');return;}
    if(c.mine.finishedAt){el(root,'p','你已交卷，答对 '+c.mine.score+'/5。等待搭子交卷后查看完整解析。','challenge-score');button(root,'刷新结果',function(session){return openChallenge(c.id,session);});return;}
    if(!c.mine.startedAt){el(root,'p','开始后计时。双方可以在不同时间完成，完整解析在双方交卷后开放。','community-muted');button(root,'开始挑战',async function(s){var r=await api('POST','challenge/start',{id:c.id});if(s===epoch){challenge=r.challenge;renderChallenge();}},true);button(root,c.creator===home.uid?'取消挑战':'婉拒挑战',async function(s){await api('PUT','challenge/cancel',{id:c.id});if(s===epoch){await openChallenge(c.id,s);await loadChallenges(s);}});return;}
    el(root,'p','剩余时间：','community-muted');var timer=el(root,'strong','');timer.id='challengeCountdown';
    var form=el(root,'form',undefined,'community-form');form.id='challengeAnswerForm';(c.questions||[]).forEach(function(q,i){var field=el(form,'fieldset',undefined,'challenge-task');el(field,'legend','第 '+(i+1)+' 题');math(el(field,'div',q.question,'community-question'));var options=el(field,'div',undefined,'challenge-options');q.options.forEach(function(value,index){var label=el(options,'label'),input=el(label,'input');input.type='radio';input.name='challenge-'+q.qid;input.value=String.fromCharCode(65+index);math(el(label,'span',input.value+' · '+value));});});
    var submit=el(form,'button','交卷并保存学习记录','btn primary');submit.type='submit';form.onsubmit=function(e){e.preventDefault();run(submit,function(s){return submitChallenge(s);});};
    function tick(){var remain=Math.max(0,15*60000-(Date.now()-c.mine.startedAt));timer.textContent=Math.floor(remain/60000)+':'+String(Math.floor(remain/1000)%60).padStart(2,'0');if(!remain){clearInterval(countdown);run(submit,function(s){return submitChallenge(s);});}}
    tick();countdown=setInterval(tick,1000);
  }
  function seconds(ms){return (Math.max(0,ms)/1000).toFixed(1)+' 秒';}
  async function submitChallenge(s){var answers={};document.querySelectorAll('#challengeAnswerForm input:checked').forEach(function(i){answers[i.name.slice(10)]=i.value;});var r=await api('POST','challenge/submit',{id:challenge.id,answers:answers});if(s!==epoch)return;challenge=r.challenge;renderChallenge();message('挑战已交卷，五道客观题已计入你的学习记录。');var merged=await WG_API.pullMerge(WG_Data.get());if(s!==epoch)return;WG_Data.replaceAll(merged);await loadChallenges(s);}
  function open(name){tab(name||'friends');StudyAppBridge.navTo('community');}
  function openQuestion(qid){scope=String(qid);clearReply();open('posts');}
  function init(){
    document.querySelectorAll('[data-community-tab]').forEach(function(b){b.onclick=function(){tab(b.dataset.communityTab);load();};b.onkeydown=function(e){if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();var nodes=Array.from(document.querySelectorAll('[data-community-tab]')),i=nodes.indexOf(b),next=e.key==='Home'?0:e.key==='End'?nodes.length-1:(i+(e.key==='ArrowRight'?1:-1)+nodes.length)%nodes.length;nodes[next].focus();nodes[next].click();};});
    $('buddyProfileForm').oninput=function(){profileDirty=true;};$('buddyProfileForm').onsubmit=function(e){e.preventDefault();run(e.submitter,async function(s){if(!cloud())return;await api('PUT','profile',{nick:$('buddyNick').value,goal:$('buddyGoal').value,availability:$('buddyAvailability').value,visible:$('buddyVisible').checked,subjects:Array.from(document.querySelectorAll('[name=buddySubject]:checked')).map(function(i){return i.value;})});if(s===epoch){profileDirty=false;await loadHome(s);message('搭子名片已保存。');}});};
    $('buddySearch').onclick=function(e){run(e.currentTarget,function(s){return loadHome(s);});};$('communityRefresh').onclick=function(e){run(e.currentTarget,async function(s){await load();if(s===epoch&&challenge&&tabName==='arena')await openChallenge(challenge.id,s);});};
    $('postResetScope').onclick=function(){scope=null;clearReply();run(this,loadPosts);};$('postCancelReply').onclick=clearReply;$('postRefresh').onclick=function(){run(this,loadPosts);};
    $('postForm').onsubmit=function(e){e.preventDefault();run(e.submitter,async function(s){if(!cloud())return;await api('POST','posts',{qid:scope,text:$('postText').value,parent:reply});if(s===epoch){$('postText').value='';clearReply();await loadPosts(s);message('留言已发布。');}});};
    $('challengeCreateForm').onsubmit=function(e){e.preventDefault();run(e.submitter,async function(s){if(!cloud())return;var r=await api('POST','challenges',{to:$('challengeFriend').value,topic:$('challengeTopic').value});if(s===epoch){message('挑战已发送。');await loadChallenges(s);await openChallenge(r.challenge.id,s);}});};$('challengeRefresh').onclick=function(){run(this,async function(s){await loadChallenges(s);if(s===epoch&&challenge)await openChallenge(challenge.id,s);});};
    WG_API.onAuthChange(function(){epoch++;loadSerial++;home=null;scope=null;reply=null;challenge=null;profileDirty=false;clearInterval(countdown);if(socket){socket.disconnect();socket=null;}$('communityConnection').textContent='实时通知待连接';$('communityNotice').hidden=true;['buddyDirectory','buddyFriends','buddyRequests','postList','postQuestion','challengeList','challengeDetail'].forEach(function(id){$(id).replaceChildren();});$('buddyProfileForm').reset();$('postForm').reset();clearReply();message('');$('buddySearchText').value='';$('buddyFilter').value='';tab('friends');fillSelect($('challengeFriend'),[],'先添加学习搭子');});
  }
  document.addEventListener('DOMContentLoaded',init);
  return{load:load,open:open,openQuestion:openQuestion};
})();
