'use strict';
window.WG_Learning = (function () {
  var $ = function(id){ return document.getElementById(id); }, epoch=0, map=null, model=null, graph=null, selected=null, plan=null, loaded=false, graphPromise=null;
  var worker=null, runId=0, runTimer=null, labResult=null, labQuestion=null, board=null, boardRequest=null;
  var api=function(method,path,body){return WG_API.req(method,'/api/learning/'+path,body);};
  function el(parent,tag,text,cls){var n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;parent.appendChild(n);return n;}
  function btn(parent,text,callback){var b=el(parent,'button',text,'btn ghost');b.type='button';b.onclick=callback;return b;}
  function message(id,value){$(id).textContent=value;}
  function cloud(id){if(WG_API.isCloudSession())return true;message(id,'请先登录云端账号，以保存你的学情、计划和草稿。');return false;}
  async function action(button,id,fn){if(button.disabled)return;var session=epoch;button.disabled=true;button.setAttribute('aria-busy','true');try{await fn(session);}catch(e){if(session===epoch)message(id,e.message||'操作失败，请重试');}finally{button.disabled=false;button.removeAttribute('aria-busy');}}
  function pct(value){return Math.round(value*100)+'%';}
  function date(value){return new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});}
  function download(name,data,type){var url=URL.createObjectURL(new Blob([data],{type:type||'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(url);},5000);}
  function math(node){if(window.renderMathInElement)renderMathInElement(node,{delimiters:[{left:'\\(',right:'\\)',display:false},{left:'\\[',right:'\\]',display:true},{left:'$$',right:'$$',display:true}],throwOnError:false,trust:false});}
  function tab(name){document.querySelectorAll('[data-learning-tab]').forEach(function(b){var on=b.dataset.learningTab===name;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;b.classList.toggle('primary',on);b.classList.toggle('ghost',!on);$('learning-'+b.dataset.learningTab).hidden=!on;});if(name==='map'&&graph){graph.resize();graph.fit(undefined,35);}if(name==='lab'&&cloud('labStatus'))loadExperiments();}
  function graphLibrary(){if(window.cytoscape)return Promise.resolve();if(!graphPromise)graphPromise=new Promise(function(resolve,reject){var script=document.createElement('script');script.src=WG_Runtime.asset('/vendor/cytoscape/cytoscape.min.js');script.onload=resolve;script.onerror=function(){graphPromise=null;reject(new Error('知识地图资源加载失败，请重新启动网站后刷新'));};document.head.appendChild(script);});return graphPromise;}
  function filtered(){return map.topics.filter(function(t){return!$('mapSubject').value||t.subject===$('mapSubject').value;});}
  function description(t){var p=model&&model.topics[t.id];return p?pct(p.mastery)+' · '+p.observations+' 次作答'+(p.observations<5?' · 样本较少':''):'未评估 · 先做几道客观题';}
  async function renderMap(){if(!map)return;await graphLibrary();var topics=filtered(),ids=topics.map(function(t){return t.id;});if(graph)graph.destroy();
    graph=cytoscape({container:$('knowledgeGraph'),elements:topics.map(function(t){var p=model&&model.topics[t.id];return{data:{id:t.id,label:t.id+'\n'+(p?pct(p.mastery):'未评估'),color:p?(p.mastery>=.8?'#268268':'#cf8948'):'#899a96'}};}).concat(map.edges.filter(function(e){return ids.includes(e[0])&&ids.includes(e[1]);}).map(function(e,i){return{data:{id:'edge-'+i,source:e[0],target:e[1]}};})),style:[{selector:'node',style:{label:'data(label)','background-color':'data(color)','font-size':11,'text-wrap':'wrap','text-max-width':100,'text-valign':'center','text-halign':'center',color:'#fff',width:115,height:54,shape:'round-rectangle'}},{selector:'edge',style:{width:1.4,'line-color':'#acc7bc','target-arrow-color':'#acc7bc','target-arrow-shape':'triangle','curve-style':'bezier'}},{selector:':selected',style:{'border-width':3,'border-color':'#133e30'}}],layout:{name:'breadthfirst',directed:true,padding:35,spacingFactor:1.2},minZoom:.25,maxZoom:2.5,wheelSensitivity:.2});
    graph.on('tap','node',function(e){showTopic(e.target.id());});$('topicList').replaceChildren();topics.forEach(function(t){btn($('topicList'),t.id+' · '+description(t),function(){showTopic(t.id);});});
    showTopic(selected&&ids.includes(selected)?selected:ids[0]);
  }
  function showTopic(id){var t=map&&map.topics.find(function(t){return t.id===id;});if(!t)return;selected=id;var detail=$('topicDetail');detail.replaceChildren();el(detail,'h2',t.id);el(detail,'p',description(t));el(detail,'p','题库 '+t.total+' 题 · 客观选择题 '+t.objective+' 题 · 错题 '+t.mistakes+' 道','integration-muted');
    var p=model&&model.topics[id];if(p)el(detail,'p','同模型估计的下一题答对概率：'+pct(p.nextCorrect)+'。这不是考试分数预测。','integration-muted');
    var actions=el(detail,'div',undefined,'learning-actions');btn(actions,'练习这个主题',function(){StudyAppBridge.practice(id);});btn(actions,'数学实验',function(){openLab(null,id);});
    el(detail,'h3','题目与推导草稿');t.samples.slice(0,4).forEach(function(q){var item=el(detail,'div');math(el(item,'p',q.question,'sample-stem'));var a=el(item,'div',undefined,'question-tools');btn(a,'作答',function(){StudyAppBridge.practice(id,q.id);});btn(a,'打开白板',function(){openBoard({qid:q.id,question:q.question,topic:id});});});
  }
  async function refresh(session){if(!cloud('learningMessage'))return;message('learningMessage','正在同步答题记录和知识地图…');await WG_API.putData(WG_Data.get());var r=await api('GET','map');if(session!==epoch)return;map=r;model=null;loaded=true;
    $('mapSubject').replaceChildren();var option=el($('mapSubject'),'option','全部课程');option.value='';Array.from(new Set(map.topics.map(function(t){return t.subject;}))).forEach(function(s){var o=el($('mapSubject'),'option',s);o.value=s;});
    $('planTopics').replaceChildren();map.topics.forEach(function(t){var label=el($('planTopics'),'label'),input=el(label,'input');input.type='checkbox';input.name='planTopic';input.value=t.id;el(label,'span',t.id);});
    await renderMap();message('learningMessage','知识地图已就绪，正在计算掌握度…');
    try{var b=await api('GET','mastery');if(session!==epoch)return;model=b;message('masterySummary','已分析 '+b.count+' 次客观作答 · '+Object.keys(b.topics).length+' 个主题有记录 · pyBKT 固定参数模型');await renderMap();message('learningMessage','学情已更新。点击地图节点或下方主题按钮开始练习。');}catch(e){if(session!==epoch)return;message('masterySummary','掌握度暂不可用：'+e.message);message('learningMessage','知识地图可继续使用。');}
    try{var result=await api('GET','plan');if(session!==epoch)return;plan=result.plan;if(plan)loadPlanConfig();renderPlan();}catch(e){if(session===epoch)message('planMessage',e.message);}
  }
  function loadPlanConfig(){var c=plan.config;$('planStartDate').value=c.startDate;$('planExamDate').value=c.examDate;$('planStartTime').value=c.startTime;$('planEndTime').value=c.endTime;$('planBlocked').value=(c.blocked||[]).map(function(b){return[b.date,b.start,b.end].join(',');}).join('\n');document.querySelectorAll('[name="planTopic"]').forEach(function(i){i.checked=(c.topics||[]).includes(i.value);});}
  async function generate(session){if(!cloud('planMessage'))return;var blocked=$('planBlocked').value.split('\n').filter(function(x){return x.trim();}).map(function(line){var p=line.replace(/，/g,',').split(',').map(function(x){return x.trim();});if(p.length!==3)throw new Error('占用时间每行填写：日期,开始,结束');return{date:p[0],start:p[1],end:p[2]};});message('planMessage','OR-Tools 正在检查可用时间并安排任务…');await WG_API.putData(WG_Data.get());var result=await api('POST','plan',{version:plan?plan.version:0,config:{startDate:$('planStartDate').value,examDate:$('planExamDate').value,startTime:$('planStartTime').value,endTime:$('planEndTime').value,blocked:blocked,topics:Array.from(document.querySelectorAll('[name="planTopic"]:checked')).map(function(i){return i.value;})}});if(session!==epoch)return;plan=result.plan;renderPlan();message('planMessage','已生成计划：'+plan.scheduled.filter(function(t){return!t.done;}).length+' 项待完成，'+plan.unscheduled.length+' 项因时间不足未安排。');}
  function renderPlan(){var area=$('planResult');area.replaceChildren();$('planExport').disabled=!plan||!plan.scheduled.length;if(!plan){el(area,'p','还没有计划。设置复习时间后开始排程。','integration-muted');return;}
    el(area,'p',plan.engine+' · '+plan.status+' · 每项 20 分钟','integration-muted');plan.scheduled.forEach(function(t){var row=el(area,'article',undefined,'plan-task');row.dataset.done=String(t.done);el(row,'strong',t.topic+' · '+t.label);el(row,'p',date(t.start)+' — '+new Date(t.end).toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour:'2-digit',minute:'2-digit'}));el(row,'p',t.reason,'integration-muted');var label=el(row,'label'),check=el(label,'input');check.type='checkbox';check.checked=t.done;el(label,'span','已完成');check.onchange=function(){var wanted=check.checked;action(check,'planMessage',async function(session){var r=await api('PUT','plan/task',{id:t.id,done:wanted,version:plan.version});if(session!==epoch)return;plan=r.plan;renderPlan();message('planMessage','任务状态已保存。');}).then(function(){if(document.contains(check))check.checked=t.done;});};var actions=el(row,'div',undefined,'learning-actions');btn(actions,'开始练习',function(){if(t.label==='到期错题复习')WG_Integrations.openQuestion(t.qid);else StudyAppBridge.practice(t.topic);});});
    if(plan.unscheduled.length){el(area,'h3','时间不足，尚未安排','plan-overflow');plan.unscheduled.forEach(function(t){el(area,'p',t.topic+' · '+t.label,'plan-overflow');});}if(!plan.scheduled.length)el(area,'p','没有可用时间段。请增加学习时间，或移除课表占用。');
  }
  function exportCalendar(){if(!plan)return;var stamp=function(v){return new Date(v).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');},escape=function(s){return s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');};var lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Xuewuyou//Study Plan//ZH','CALSCALE:GREGORIAN'];plan.scheduled.forEach(function(t){lines.push('BEGIN:VEVENT','UID:'+encodeURIComponent(t.id)+'-'+plan.version+'@xuewuyou','DTSTAMP:'+stamp(plan.createdAt),'DTSTART:'+stamp(t.start),'DTEND:'+stamp(t.end),'SUMMARY:'+escape(t.topic+' · '+t.label),'DESCRIPTION:'+escape(t.reason),'END:VEVENT');});lines.push('END:VCALENDAR');download('学无忧备考计划.ics',lines.join('\r\n')+'\r\n','text/calendar;charset=utf-8');}
  var templates={
    calculus:"import sympy as sp\nx = sp.symbols('x')\nf = sp.sin(x) * sp.exp(x)\nprint('f(x) =', f)\nprint('导数:', sp.diff(f, x))\nprint('定积分:', sp.integrate(f, (x, 0, sp.pi)))\nprint('数值:', sp.N(sp.integrate(f, (x, 0, sp.pi))))",
    matrix:"import sympy as sp\nA = sp.Matrix([[2, 1], [1, 2]])\nprint('矩阵:'); sp.pprint(A)\nprint('行列式:', A.det())\nprint('特征值:', A.eigenvals())\nprint('逆矩阵:'); sp.pprint(A.inv())",
    probability:"import numpy as np\nimport matplotlib.pyplot as plt\nrng = np.random.default_rng(42)\nx = rng.normal(0, 1, 10000)\nprint('样本均值:', float(x.mean()))\nprint('样本标准差:', float(x.std()))\nprint('P(|X| < 1) 的模拟估计:', float(np.mean(np.abs(x) < 1)))\nplt.hist(x, bins=45, density=True, color='#31836b')\nplt.title('Standard normal simulation'); plt.grid(alpha=0.2)",
    plot:"import numpy as np\nimport matplotlib.pyplot as plt\nx = np.linspace(-4, 4, 400)\nplt.plot(x, x**2, label='x^2', color='#31836b')\nplt.plot(x, 2*x, label='derivative: 2x', color='#cc8240')\nplt.axhline(0, color='gray', linewidth=0.5)\nplt.legend(); plt.grid(alpha=0.2)\nprint('函数曲线与导函数，用图像核对变化趋势。')"
  };
  function templateFor(topic){return /矩阵|向量|行列|二次型|方程组|对角化|特征值/.test(topic)?'matrix':/随机|概率|参数|数字特征|检验|大数/.test(topic)?'probability':'calculus';}
  function openLab(q,topic){stopLab();labQuestion=q||null;StudyAppBridge.navTo('learning');tab('lab');message('labContext',q?'关联题目 '+q.qid+' · '+q.topic+'：'+q.question:(topic||'自由实验'));$('labTemplate').value=templateFor(topic||q&&q.topic||'');$('labCode').value=templates[$('labTemplate').value];labResult=null;$('labSave').disabled=true;}
  function stopLab(status){if(worker){worker.terminate();worker=null;}clearTimeout(runTimer);runId++;$('labRun').disabled=false;$('labStop').disabled=true;if(status)message('labStatus',status);}
  function runLab(){if($('labRun').disabled)return;labResult=null;$('labSave').disabled=true;$('labRun').disabled=true;$('labStop').disabled=false;$('labOutput').textContent='';$('labImages').replaceChildren();message('labStatus','正在准备本地 Python 环境与科学计算库…');var id=++runId,session=epoch;
    var resultQid=labQuestion?labQuestion.qid:null;
    if(!worker)worker=new Worker(WG_Runtime.asset('/js/math-worker.js'),{type:'module'});worker.onmessage=function(e){if(session!==epoch||id!==runId)return;var r=e.data;if(r.type==='status'){message('labStatus',r.message);if(r.message==='正在运行代码…'){clearTimeout(runTimer);runTimer=setTimeout(function(){stopLab('运行超过 20 秒，已停止。可修改代码后再次运行。');},20000);}return;}if(r.type==='result'){clearTimeout(runTimer);$('labRun').disabled=false;$('labStop').disabled=true;labResult={code:r.code,output:r.output,images:r.images||[],error:r.error,qid:resultQid};$('labOutput').textContent=r.output;renderImages(r.images||[]);message('labStatus',r.error?'代码运行出错，请检查下方信息。':'运行完成 · '+r.elapsed+' ms');$('labSave').disabled=!!r.error;}else if(r.type==='error'){stopLab('运行环境加载失败：'+r.message);}};
    worker.onerror=function(){stopLab('Python 工作线程发生错误，请重试。');};runTimer=setTimeout(function(){stopLab('运行环境初始化超时，请刷新重试。');},90000);worker.postMessage({code:$('labCode').value});
  }
  function renderImages(images){$('labImages').replaceChildren();images.forEach(function(url,i){var img=el($('labImages'),'img');img.src=url;img.alt='实验输出图 '+(i+1);btn($('labImages'),'下载图 '+(i+1),function(){var a=document.createElement('a');a.href=url;a.download='数学实验-'+(i+1)+'.png';a.click();});});}
  async function saveLab(session){if(!cloud('labStatus')||!labResult||labResult.error)return;await api('POST','experiment',{title:$('labTitle').value,code:labResult.code,output:labResult.output,images:labResult.images,qid:labResult.qid});if(session!==epoch)return;message('labStatus','实验结果已保存，可重新打开与复现。');await loadExperiments();}
  async function loadExperiments(){var session=epoch;try{var r=await api('GET','experiments');if(session!==epoch)return;var list=$('labHistory');list.replaceChildren();if(!r.experiments.length)el(list,'p','还没有保存的实验。','integration-muted');r.experiments.forEach(function(m){var row=el(list,'article',undefined,'experiment-entry');el(row,'strong',m.title);el(row,'p',date(m.createdAt)+(m.qid?' · 题号 '+m.qid:''),'integration-muted');var actions=el(row,'div',undefined,'learning-actions');btn(actions,'打开实验',function(e){action(e.currentTarget,'labStatus',async function(s){var v=(await api('GET','experiment?id='+encodeURIComponent(m.id))).experiment;if(s!==epoch)return;stopLab();$('labCode').value=v.code;$('labTitle').value=v.title;$('labOutput').textContent=v.output;renderImages(v.images);labQuestion=v.qid?{qid:v.qid}:null;message('labContext',v.qid?'关联题目 '+v.qid:'自由实验');labResult={code:v.code,output:v.output,images:v.images,qid:v.qid};$('labSave').disabled=false;message('labStatus','已载入保存结果；修改代码后运行可复现。');});});btn(actions,'删除',function(e){action(e.currentTarget,'labStatus',async function(s){await api('DELETE','experiment',{id:m.id});if(s===epoch)await loadExperiments();});});});}catch(e){if(session===epoch)message('labStatus',e.message);}}
  async function openBoard(q){if(!cloud('learningMessage')){alert('请登录云端账号后打开题目白板。');return;}if(board)return;var session=epoch;board={qid:String(q.qid||q.id),question:q.question,version:0,ready:false};message('boardQuestion','题号 '+board.qid+' · '+(q.topic||'')+'\n'+(q.question||''));message('boardStatus','正在读取这道题的草稿…');$('boardSave').disabled=true;$('boardExport').disabled=true;$('questionBoardDialog').showModal();
    try{var r=await api('GET','board?id='+encodeURIComponent(board.qid));if(session!==epoch||!board)return;board.version=r.board.version;board.scene=r.board;var frame=document.createElement('iframe');frame.title='Excalidraw 题目专属草稿白板';frame.src=WG_Runtime.asset('/vendor/whiteboard/index.html');$('boardFrameHost').replaceChildren(frame);board.frame=frame;message('boardStatus','正在加载白板…');}catch(e){if(session===epoch)message('boardStatus',e.message);}
  }
  function requestScene(){if(!board||!board.ready)return Promise.reject(new Error('白板尚未加载完成'));if(boardRequest)return Promise.reject(new Error('正在读取白板，请稍后'));return new Promise(function(resolve,reject){var timer=setTimeout(function(){boardRequest=null;reject(new Error('白板响应超时，请导出或重试'));},5000);boardRequest={resolve:function(v){clearTimeout(timer);boardRequest=null;resolve(v);},reject:function(){clearTimeout(timer);boardRequest=null;reject(new Error('白板已关闭'));}};board.frame.contentWindow.postMessage({type:'xwy:scene-request'},location.origin);});}
  async function saveBoard(session){if(!board||!board.ready)throw new Error('白板尚未加载完成');var target=board,snapshot=await requestScene();if(session!==epoch||board!==target)return;var r=await api('PUT','board',{qid:target.qid,version:target.version,elements:snapshot.elements,appState:snapshot.appState,files:snapshot.files});if(session!==epoch||board!==target)return;board.version=r.version;message('boardStatus','草稿已保存 · '+new Date(r.updatedAt).toLocaleTimeString('zh-CN'));}
  async function closeBoard(){if($('boardClose').disabled)return;await action($('boardClose'),'boardStatus',async function(session){if(board&&board.ready)await saveBoard(session);if(session!==epoch)return;board=null;boardRequest&&boardRequest.reject();$('boardFrameHost').replaceChildren();$('questionBoardDialog').close();});}
  window.addEventListener('message',function(e){if(e.origin!==location.origin||!board||!board.frame||e.source!==board.frame.contentWindow)return;var r=e.data;if(r.type==='xwy:ready'){board.frame.contentWindow.postMessage({type:'xwy:load',scene:board.scene},location.origin);}else if(r.type==='xwy:loaded'){board.ready=true;$('boardSave').disabled=false;$('boardExport').disabled=false;message('boardStatus','这道题的草稿已加载。关闭时自动保存，也可随时点击保存。');}else if(r.type==='xwy:scene'&&boardRequest)boardRequest.resolve(r.scene);else if(r.type==='xwy:dirty'){message('boardStatus','草稿有修改 · 关闭时自动保存');}else if(r.type==='xwy:png'){download('题目-'+board.qid+'-草稿.png',r.blob,'image/png');}else if(r.type==='xwy:error'){message('boardStatus',r.message);}});
  function attachQuestion(parent,q){if(!q||!(q.qid||q.id))return;var old=parent.querySelector('.question-tools');if(old)old.remove();var tools=el(parent,'div',undefined,'question-tools');btn(tools,'题目白板',function(){openBoard(q);});btn(tools,'数学实验',function(){openLab(q,q.topic);});btn(tools,'题目讨论',function(){window.WG_Community&&WG_Community.openQuestion(String(q.qid||q.id));});}
  function reset(){epoch++;loaded=false;map=null;model=null;plan=null;selected=null;if(graph){graph.destroy();graph=null;}stopLab();labResult=null;labQuestion=null;board=null;boardRequest&&boardRequest.reject();$('boardFrameHost').replaceChildren();$('questionBoardDialog').close();['topicDetail','topicList','masterySummary','labOutput','labImages','labHistory','planResult'].forEach(function(id){$(id).replaceChildren();});$('labCode').value=templates.calculus;$('labSave').disabled=true;$('planExport').disabled=true;}
  document.querySelectorAll('[data-learning-tab]').forEach(function(b){b.onclick=function(){tab(b.dataset.learningTab);};b.onkeydown=function(e){if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();var tabs=Array.from(document.querySelectorAll('[data-learning-tab]')),i=tabs.indexOf(b),next=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tab(tabs[next].dataset.learningTab);tabs[next].focus();};});
  $('learningRefresh').onclick=function(e){action(e.currentTarget,'learningMessage',refresh);};$('mapSubject').onchange=function(){renderMap().catch(function(e){message('learningMessage',e.message);});};$('mapFit').onclick=function(){if(graph)graph.fit(undefined,35);};
  $('mapZoomIn').onclick=function(){if(graph)graph.zoom({level:Math.min(graph.maxZoom(),graph.zoom()*1.35),renderedPosition:{x:graph.width()/2,y:graph.height()/2}});};$('mapZoomOut').onclick=function(){if(graph)graph.zoom({level:Math.max(graph.minZoom(),graph.zoom()/1.35),renderedPosition:{x:graph.width()/2,y:graph.height()/2}});};
  $('planForm').onsubmit=function(e){e.preventDefault();action($('planGenerate'),'planMessage',generate);};$('planExport').onclick=exportCalendar;
  var today=new Date(Date.now()+8*3600000).toISOString().slice(0,10);$('planStartDate').value=today;$('planExamDate').value=new Date(Date.parse(today)+6*86400000).toISOString().slice(0,10);$('planStartDate').min=today;
  $('labCode').value=templates.calculus;$('labLoadTemplate').onclick=function(){$('labCode').value=templates[$('labTemplate').value];labResult=null;$('labSave').disabled=true;};$('labCode').oninput=function(){$('labSave').disabled=true;};$('labClearContext').onclick=function(){labQuestion=null;message('labContext','自由实验');};$('labRun').onclick=runLab;$('labStop').onclick=function(){stopLab('已停止运行，修改代码后可再次运行。');};$('labSave').onclick=function(e){action(e.currentTarget,'labStatus',saveLab);};$('labCodeExport').onclick=function(){download('数学实验.py',$('labCode').value);};
  $('boardSave').onclick=function(e){action(e.currentTarget,'boardStatus',saveBoard);};$('boardClose').onclick=closeBoard;$('questionBoardDialog').addEventListener('cancel',function(e){e.preventDefault();closeBoard();});$('boardExport').onclick=function(){if(board&&board.ready)board.frame.contentWindow.postMessage({type:'xwy:export-png'},location.origin);};
  WG_API.onAuthChange(reset);
  return{open:function(){if(!loaded)action($('learningRefresh'),'learningMessage',refresh);else if(graph)setTimeout(function(){graph.resize();},0);},attachQuestion:attachQuestion,openBoard:openBoard,openLab:openLab};
})();
