'use strict';
window.WG_Whiteboard = (function () {
  var $=function(id){return document.getElementById(id);},epoch=0,board=null,boardRequest=null;
  var api=function(method,path,body){return WG_API.req(method,'/api/learning/'+path,body);};
  function message(id,value){$(id).textContent=value;}
  function el(parent,tag,text,cls){var n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;parent.appendChild(n);return n;}
  function btn(parent,text,callback){var b=el(parent,'button',text,'btn ghost');b.type='button';b.onclick=callback;return b;}
  async function action(button,id,fn){if(button.disabled)return;var session=epoch;button.disabled=true;button.setAttribute('aria-busy','true');try{await fn(session);}catch(e){if(session===epoch)message(id,e.message||'操作失败，请重试');}finally{button.disabled=false;button.removeAttribute('aria-busy');}}
  function download(name,data,type){var url=URL.createObjectURL(new Blob([data],{type:type||'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(url);},5000);}
  async function openBoard(q){if(!WG_API.isCloudSession()){alert('请登录云端账号后打开题目白板。');return;}if(board)return;var session=epoch;board={qid:String(q.qid||q.id),question:q.question,version:0,ready:false};message('boardQuestion','题号 '+board.qid+' · '+(q.topic||'')+'\n'+(q.question||''));message('boardStatus','正在读取这道题的草稿…');$('boardSave').disabled=true;$('boardExport').disabled=true;$('questionBoardDialog').showModal();
    try{var r=await api('GET','board?id='+encodeURIComponent(board.qid));if(session!==epoch||!board)return;board.version=r.board.version;board.scene=r.board;var frame=document.createElement('iframe');frame.title='Excalidraw 题目专属草稿白板';frame.src=WG_Runtime.asset('/vendor/whiteboard/index.html');$('boardFrameHost').replaceChildren(frame);board.frame=frame;message('boardStatus','正在加载白板…');}catch(e){if(session===epoch)message('boardStatus',e.message);}
  }
  function requestScene(){if(!board||!board.ready)return Promise.reject(new Error('白板尚未加载完成'));if(boardRequest)return Promise.reject(new Error('正在读取白板，请稍后'));return new Promise(function(resolve,reject){var timer=setTimeout(function(){boardRequest=null;reject(new Error('白板响应超时，请导出或重试'));},5000);boardRequest={resolve:function(v){clearTimeout(timer);boardRequest=null;resolve(v);},reject:function(){clearTimeout(timer);boardRequest=null;reject(new Error('白板已关闭'));}};board.frame.contentWindow.postMessage({type:'xwy:scene-request'},location.origin);});}
  async function saveBoard(session){if(!board||!board.ready)throw new Error('白板尚未加载完成');var target=board,snapshot=await requestScene();if(session!==epoch||board!==target)return;var r=await api('PUT','board',{qid:target.qid,version:target.version,elements:snapshot.elements,appState:snapshot.appState,files:snapshot.files});if(session!==epoch||board!==target)return;board.version=r.version;message('boardStatus','草稿已保存 · '+new Date(r.updatedAt).toLocaleTimeString('zh-CN'));}
  async function closeBoard(){if($('boardClose').disabled)return;await action($('boardClose'),'boardStatus',async function(session){if(board&&board.ready)await saveBoard(session);if(session!==epoch)return;board=null;boardRequest&&boardRequest.reject();$('boardFrameHost').replaceChildren();$('questionBoardDialog').close();});}
  window.addEventListener('message',function(e){if(e.origin!==location.origin||!board||!board.frame||e.source!==board.frame.contentWindow)return;var r=e.data;if(r.type==='xwy:ready'){board.frame.contentWindow.postMessage({type:'xwy:load',scene:board.scene},location.origin);}else if(r.type==='xwy:loaded'){board.ready=true;$('boardSave').disabled=false;$('boardExport').disabled=false;message('boardStatus','这道题的草稿已加载。关闭时自动保存，也可随时点击保存。');}else if(r.type==='xwy:scene'&&boardRequest)boardRequest.resolve(r.scene);else if(r.type==='xwy:dirty'){message('boardStatus','草稿有修改 · 关闭时自动保存');}else if(r.type==='xwy:png'){download('题目-'+board.qid+'-草稿.png',r.blob,'image/png');}else if(r.type==='xwy:error'){message('boardStatus',r.message);}});
  function attachQuestion(parent,q){if(!q||!(q.qid||q.id))return;var old=parent.querySelector('.question-tools');if(old)old.remove();var tools=el(parent,'div',undefined,'question-tools');btn(tools,'题目白板',function(){openBoard(q);});btn(tools,'题目讨论',function(){window.WG_Community&&WG_Community.openQuestion(String(q.qid||q.id));});}
  function reset(){epoch++;board=null;boardRequest&&boardRequest.reject();$('boardFrameHost').replaceChildren();$('questionBoardDialog').close();message('boardQuestion','');message('boardStatus','');$('boardSave').disabled=true;$('boardExport').disabled=true;}
  $('boardSave').onclick=function(e){action(e.currentTarget,'boardStatus',saveBoard);};$('boardClose').onclick=closeBoard;$('questionBoardDialog').addEventListener('cancel',function(e){e.preventDefault();closeBoard();});$('boardExport').onclick=function(){if(board&&board.ready)board.frame.contentWindow.postMessage({type:'xwy:export-png'},location.origin);};
  WG_API.onAuthChange(reset);
  return {attachQuestion:attachQuestion,openBoard:openBoard};
})();
