'use strict';
const fs = require('fs');
const path = require('path');
const src = path.dirname(require.resolve('katex/dist/katex.min.js'));
const dest = path.join(__dirname, '../../vendor/katex');
fs.mkdirSync(path.join(dest, 'contrib'), { recursive: true });
for (const filename of ['katex.min.js', 'katex.min.css']) fs.copyFileSync(path.join(src, filename), path.join(dest, filename));
fs.copyFileSync(path.join(src, 'contrib/auto-render.min.js'), path.join(dest, 'contrib/auto-render.min.js'));
fs.copyFileSync(path.join(src, '../LICENSE'), path.join(dest, 'LICENSE'));
fs.cpSync(path.join(src, 'fonts'), path.join(dest, 'fonts'), { recursive: true });
const cytoscapeDir = path.join(__dirname, '../../vendor/cytoscape');
fs.mkdirSync(cytoscapeDir, { recursive:true });
fs.copyFileSync(require.resolve('cytoscape/dist/cytoscape.min.js'), path.join(cytoscapeDir,'cytoscape.min.js'));
fs.copyFileSync(path.join(path.dirname(require.resolve('cytoscape')),'../LICENSE'), path.join(cytoscapeDir,'LICENSE'));
const phaserDir = path.join(__dirname,'../../vendor/phaser');
fs.mkdirSync(phaserDir,{recursive:true});
const phaserPackage = path.dirname(require.resolve('phaser/package.json'));
fs.copyFileSync(path.join(phaserPackage,'dist/phaser.min.js'),path.join(phaserDir,'phaser.min.js'));
fs.copyFileSync(path.join(phaserPackage,'LICENSE.md'),path.join(phaserDir,'LICENSE.md'));
const socketPackage=path.join(path.dirname(require.resolve('socket.io')),'..');
const socketDir=path.join(__dirname,'../../vendor/socketio');fs.mkdirSync(socketDir,{recursive:true});
fs.copyFileSync(path.join(socketPackage,'client-dist/socket.io.min.js'),path.join(socketDir,'socket.io.min.js'));
fs.copyFileSync(path.join(socketPackage,'LICENSE'),path.join(socketDir,'LICENSE'));
const markdownPackage=path.join(path.dirname(require.resolve('markdown-it')),'..');
const markdownDir=path.join(__dirname,'../../vendor/markdown-it');fs.mkdirSync(markdownDir,{recursive:true});
fs.copyFileSync(path.join(markdownPackage,'dist/browser/markdown-it.umd.min.js'),path.join(markdownDir,'markdown-it.min.js'));
fs.copyFileSync(path.join(markdownPackage,'LICENSE'),path.join(markdownDir,'LICENSE'));
